apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-monitoring-frontend
  namespace: health-app-dev
  labels:
    app: health-monitoring-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-monitoring-frontend
  template:
    metadata:
      labels:
        app: health-monitoring-frontend
    spec:
      containers:
        - name: health-monitoring-frontend
          image: health-monitoring-frontend:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "non-production"
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"