// Auth Action Types
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';

export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';

export const AUTH_GITHUB_REQUEST = 'AUTH_GITHUB_REQUEST';
export const AUTH_GITHUB_SUCCESS = 'AUTH_GITHUB_SUCCESS';
export const AUTH_GITHUB_FAILURE = 'AUTH_GITHUB_FAILURE';

export const AUTH_LOGOUT_REQUEST = 'AUTH_LOGOUT_REQUEST';
export const AUTH_LOGOUT_SUCCESS = 'AUTH_LOGOUT_SUCCESS';
export const AUTH_LOGOUT_FAILURE = 'AUTH_LOGOUT_FAILURE';

export const AUTH_UPDATE_PROFILE_REQUEST = 'AUTH_UPDATE_PROFILE_REQUEST';
export const AUTH_UPDATE_PROFILE_SUCCESS = 'AUTH_UPDATE_PROFILE_SUCCESS';
export const AUTH_UPDATE_PROFILE_FAILURE = 'AUTH_UPDATE_PROFILE_FAILURE';

export const AUTH_CLEAR_ERROR = 'AUTH_CLEAR_ERROR';
export const AUTH_RESTORE_SESSION = 'AUTH_RESTORE_SESSION';

// Health Metrics Action Types
export const HEALTH_FETCH_METRICS_REQUEST = 'HEALTH_FETCH_METRICS_REQUEST';
export const HEALTH_FETCH_METRICS_SUCCESS = 'HEALTH_FETCH_METRICS_SUCCESS';
export const HEALTH_FETCH_METRICS_FAILURE = 'HEALTH_FETCH_METRICS_FAILURE';

export const HEALTH_FETCH_GOALS_REQUEST = 'HEALTH_FETCH_GOALS_REQUEST';
export const HEALTH_FETCH_GOALS_SUCCESS = 'HEALTH_FETCH_GOALS_SUCCESS';
export const HEALTH_FETCH_GOALS_FAILURE = 'HEALTH_FETCH_GOALS_FAILURE';

export const HEALTH_CREATE_GOAL_REQUEST = 'HEALTH_CREATE_GOAL_REQUEST';
export const HEALTH_CREATE_GOAL_SUCCESS = 'HEALTH_CREATE_GOAL_SUCCESS';
export const HEALTH_CREATE_GOAL_FAILURE = 'HEALTH_CREATE_GOAL_FAILURE';

export const HEALTH_FETCH_ALERTS_REQUEST = 'HEALTH_FETCH_ALERTS_REQUEST';
export const HEALTH_FETCH_ALERTS_SUCCESS = 'HEALTH_FETCH_ALERTS_SUCCESS';
export const HEALTH_FETCH_ALERTS_FAILURE = 'HEALTH_FETCH_ALERTS_FAILURE';

export const HEALTH_CREATE_ALERT_REQUEST = 'HEALTH_CREATE_ALERT_REQUEST';
export const HEALTH_CREATE_ALERT_SUCCESS = 'HEALTH_CREATE_ALERT_SUCCESS';
export const HEALTH_CREATE_ALERT_FAILURE = 'HEALTH_CREATE_ALERT_FAILURE';

export const HEALTH_FETCH_SERVICES_REQUEST = 'HEALTH_FETCH_SERVICES_REQUEST';
export const HEALTH_FETCH_SERVICES_SUCCESS = 'HEALTH_FETCH_SERVICES_SUCCESS';
export const HEALTH_FETCH_SERVICES_FAILURE = 'HEALTH_FETCH_SERVICES_FAILURE';

export const HEALTH_CLEAR_ERROR = 'HEALTH_CLEAR_ERROR';
