apiVersion: v1
kind: Service
metadata:
  name: health-monitoring-frontend-service
  labels:
    app: health-monitoring-frontend
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 3000   # or your app port