apiVersion: v1
kind: Service
metadata:
  name: health-monitoring-frontend-service
  labels:
    app: health-monitoring-frontend
spec:
  type: NodePort
  selector:
    app: health-monitoring-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30001